name: JetsMinions-Fixer
author: Geik
main: xyz.geik.minion.fixer.Main
version: 1.0.0
api-version: 1.13
depend: [JetsMinions]
softdepend: [ASkyBlock, SuperiorSkyblock]
commands:
   miniongeik:
      description: remove area limit